### ISSUE TITLE
Обсуждение: язык разработки проекта

### ISSUE THREAD

**Issue by codedokode** [phpclubtech/phpClub#94]
Нет, речь не про языки программирования. Я предлагаю обсудить выбор языка, на котором пишутся: 

- комментарии в коде
- документация
- названия коммитов

(для каждого пункта можно предложить свой язык).

Сейчас де-факто везде используется английский, и вот, какие я вижу плюсы и минусы: 

- использование английского в ридми (который человек видит, зайдя в репозиторий) может отпугивать от изучения кода или участия в разработке тех, кто его пока плохо знает
- если человек не очень хорошо знает английский, то он будет избегать написания подробных и длинных комментариев в коде, которые ему трудно сформулировать. Сейчас, например, в коде с комментариями все довольно печально - их почти нет. 
- использование английского позволяет попрактиковаться в нем, тем более, что во многих компаниях требуется его использовать. У нас все по-настоящему!
- если комментарии писать на русском, то нельзя будет вынести код в открытую библиотеку (ну то есть можно, но иностранные разработчики и пользователи столкнутся с трудностями)
- английский позволяет участвовать в проекте разработчикам со всего мира
- но контент на сайте только русскоязычный, и поддерживаются только русскоязычные имиджборды 

Было бы интересно услышать мнение, и тех, кто участвует в проекте, и может быть тех, кто просто тихонечко заходит посмотреть, как он развивается. Если у вас нет аргументов, можно просто написать личные предпочтения.

Этот issue создан в первую очередь для обсуждения. Я не призываю сейчас что-то менять.

**Comment by kubk** [comment]
Обсуждали когда-то что-то похожее в гиттере. Вообще, по-моему, для такого проекта нужно по максимуму все обсуждения выносить из закрытых групп в issue на гитхабе, чтобы любое issue/обсуждение в будущем можно было найти. Превосходно когда коммиты связаны с issue (гитхаб легко позволяет это делать: https://help.github.com/articles/closing-issues-using-keywords/). А в чате из тысячи сообщений никто ничего искать не будет. Кстати, есть один довольно эпатажный человек, который полностью запрещает чаты для проектов: https://www.yegor256.com/2014/10/07/stop-chatting-start-coding.html
Не могу точно найти статью, но основная мысль в том, что issue и пулл реквесты являются единым каналом коммуникации, что позволяет информации не теряться.

Моё мнение - ридми и обсуждения в issue на русском, коммиты на английском. Какие-то подробные комментарии или документацию можно писать на русском и добавлять их в папку `/docs`. В коде, как и в коммитах, русский язык очень непривычно смотрится.

**Comment by spudro228** [comment]
Рекомендую обратить внимание на [gitflow](https://danielkummer.github.io/git-flow-cheatsheet/index.ru_RU.html)

Коммитыты делать: #ISSUE_ID - some_task_name

А к коду желательно не писать, коменты конечно, код без них должен быть понятен) 
Но если понадобится вылить либу в попенсорс, то можно просто потом перевести на ангельский и тупа взять phpDocumentor 
(имхо гавно с коментами не стоит свечь)

**Comment by spudro228** [comment]
UPD: Имхо yegor256 просто уебок)

**Comment by kubk** [comment]
В итоге пришли к такому формату - README на русском, обсуждения в задачах тоже. Названия коммитов на английском.
